### ISSUE TITLE
Create a module when creating a structure

### ISSUE THREAD

**Issue by shiroyasha** [ejpcmac/typed_struct#17]
Awesome library. I enjoy using it. Kudos!
I replaced our internal implementations of a typed struct, with this library.

One thing that is a slight annoyance is the boilerplate when defining nested structures. 

Here is a toy example:

``` elixir
defmodule User do
  use TypedStruct

  typedstruct do
    field(:name, String.t())
    field(:addres, Address.t())
  end

  defmodule Address do
    use TypedStruct

    typedstruct do
        field(:street_name, String.t())
        field(:city, String.t())
    end
  end
end
```

@ejpcmac What do you thing of a syntax that creates a module with a structure like in this example:

``` elixir
defmodule User do
  use TypedStruct

  typedstruct do
    field(:name, String.t())
    field(:addres, Address.t())
  end
  
  typedstruct(Address) do
     field(:street_name, String.t())
     field(:city, String.t())
  end
end
```

In a real world example I usually see dozens of substructures, and the boilerplate adds up and reduces readability.

---

Would you be interested in a PR that introduces this posibility? Or maybe somehow via a plugin if it is possible?

I would be glad to write the code, but I don't want to start before I have a green light from you.

**Comment by ejpcmac** [comment]
Hi @shiroyasha!

This is indeed a pretty good idea, and as it can be a quite common case, I think it has its place in TypedStruct itself. We just need to ensure creating a new module directly via the `typedstruct` macro does not add some strange edge case.

For the API, I would prefer:

```elixir
defmodule User do
  use TypedStruct

  typedstruct do
    field :name, String.t()
    field :addres, Address.t()
  end
  
  typedstruct module: Address do
     field :street_name, String.t()
     field :city, String.t()
  end
end
```

I’m not even sure the one you’ve proposed is possible, since the `do` block is already an argument for the `typedstruct` macro, so closing the parenthesis before the `do` is quite strange. Plus `typedstruct/2` already exists and adding a new option is quit straightforward.

Feel free to do a PR, I’ll have some bandwidth to review and merge it at the end of the week or next week-end.

*Edit: I’ve just bumped the version to `0.2.1-dev` on `develop`. You can base on this branch and ask for merging your PR on it.*

**Comment by ejpcmac** [comment]
@shiroyasha I’m sorry: I started to try things in the code, got caught by it, and now I’m done with an implementation. Just need to update the docs and release.

**Comment by ejpcmac** [comment]
TypedStruct 0.2.1 is now on hex.pm.

**Comment by shiroyasha** [comment]
Awesome! Thanks for implementing this @ejpcmac. 🙇

**Comment by ejpcmac** [comment]
> Awesome! Thanks for implementing this @ejpcmac. 🙇

You’re welcome :)

**Comment by shiroyasha** [comment]
As a side-topic followup :)

@ejpcmac what is your opinion about enums in Elixir, more specifically, enums in the context of typed_structs?

This is something that I often miss in Elixir.

**Comment by ejpcmac** [comment]
Usually when I need something like a C enum in Elixir, I use atoms and define a type:

```elixir
@type my_enum() :: :choice_a | :choice_b | :choice_c

typedstruct do
  field :enum_field, my_enum()
end
```

I don’t really miss them, I mean, not more than static types—which I miss a bit.

You can even do Rust-like enums, but untyped and unnamed, like this:

```elixir
defmodule MyOtherStruct do
  use TypedStruct

  @type my_enum() :: :choice_a | integer() | MyStruct.t()

  typedstruct do
    field :enum_field, my_enum()
  end
end
```

Then you can use pattern-matching to handle the different cases when treating `MyOtherStruct.t()` data. But, yes, it isn’t quite as beautiful as what you can do with Rust.

Like for any customised pattern-matching on typed structs, generating functions for this could be done by a TypedStruct plugin.
